--                     LAB 7

create table Report (
id number generated by default as identity primary key ,
xml_column XMLType 
);

--				Task 2
create or replace procedure generateXML 
as
    x xmlType;
begin
    select  XMLRoot(xmlelement("Report",
                    
                                        xmlagg(
                                                xmlelement(
                                                            "row", XMLATTRIBUTES ("Customer", "RouteName", "RouteCount", "Date")
                                                          )
                                               )
                                )
                                         
                                    , VERSION'1.0', STANDALONE YES
                  )
    into x
    from   
    (Select "Customer", "RouteName", "RouteCount", sysdate "Date"
    from 
    (
        SELECT A.CustomerName "Customer", B.RouteName "RouteName", COUNT(A.RouteName) "RouteCount" FROM 
        (
            (SELECT CustomerName, ServiceType, UnitsAmount, RouteName from Order_ inner join Service on ServiceId = Service.Id)  "A" right outer join 
            (SELECT RouteName from Route) "B" on A.RouteName = B.RouteName
        )
        Group By A.CustomerName , B.RouteName
    ) "final" where "Customer" is not null);
    dbms_output.put_line(x.getClobVal());
end;

go
execute generateXML;

--				Task 3
create or replace procedure insertXMLintoTable 
as
    x xmlType;
begin 
    select  XMLRoot(xmlelement("Report",
                    
                                        xmlagg(
                                                xmlelement(
                                                            "row", XMLATTRIBUTES ("Customer", "RouteName", "RouteCount", "Date")
                                                          )
                                               )
                                )
                                         
                                    , VERSION'1.0', STANDALONE YES
                  )
    into x
    from   
    (Select "Customer", "RouteName", "RouteCount", sysdate "Date"
    from 
    (
        SELECT A.CustomerName "Customer", B.RouteName "RouteName", COUNT(A.RouteName) "RouteCount" FROM 
        (
            (SELECT CustomerName, ServiceType, UnitsAmount, RouteName from Order_ inner join Service on ServiceId = Service.Id)  "A" right outer join 
            (SELECT RouteName from Route) "B" on A.RouteName = B.RouteName
        )
        Group By A.CustomerName , B.RouteName
    ) "final" where "Customer" is not null);
insert into Report(xml_column) values(x);
end;

execute insertXMLintoTable
select id, EXTRACT(xml_column,'/Report').getClobVal() from Report;

--				Task 4
create index XMLIndexOne on Report(Xml_column)
indextype is XDB.XMLIndex
parameters ('paths (include (/Report/row))');
--				Task 5
create or replace procedure SelectData(queryS varchar2)
is
  CURSOR MYCURS IS select EXTRACT(xml_column,queryS).getClobVal() from Report;
  querR CLOB;
begin
OPEN MYCURS;
  FETCH MYCURS INTO querR;
       DBMS_OUTPUT.PUT_LINE(querR);

  CLOSE MYCURS;
  EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(sqlerrm);
end;

begin
    execute SelectData('/Report/row');
    execute SelectData('/Report/row[@RouteName = "Витебск-Минск"]');
    execute SelectData('/Report/row[3]');
end;